// Work Items Action Types
export const FETCH_WORK_ITEMS_START = 'FETCH_WORK_ITEMS_START';
export const FETCH_WORK_ITEMS_SUCCESS = 'FETCH_WORK_ITEMS_SUCCESS';
export const FETCH_WORK_ITEMS_ERROR = 'FETCH_WORK_ITEMS_ERROR';

export const CREATE_WORK_ITEM_START = 'CREATE_WORK_ITEM_START';
export const CREATE_WORK_ITEM_SUCCESS = 'CREATE_WORK_ITEM_SUCCESS';
export const CREATE_WORK_ITEM_ERROR = 'CREATE_WORK_ITEM_ERROR';

export const UPDATE_WORK_ITEM_START = 'UPDATE_WORK_ITEM_START';
export const UPDATE_WORK_ITEM_SUCCESS = 'UPDATE_WORK_ITEM_SUCCESS';
export const UPDATE_WORK_ITEM_ERROR = 'UPDATE_WORK_ITEM_ERROR';

// Agents Action Types
export const FETCH_AGENTS_START = 'FETCH_AGENTS_START';
export const FETCH_AGENTS_SUCCESS = 'FETCH_AGENTS_SUCCESS';
export const FETCH_AGENTS_ERROR = 'FETCH_AGENTS_ERROR';

export const CREATE_AGENT_START = 'CREATE_AGENT_START';
export const CREATE_AGENT_SUCCESS = 'CREATE_AGENT_SUCCESS';
export const CREATE_AGENT_ERROR = 'CREATE_AGENT_ERROR';

export const STOP_AGENT_START = 'STOP_AGENT_START';
export const STOP_AGENT_SUCCESS = 'STOP_AGENT_SUCCESS';
export const STOP_AGENT_ERROR = 'STOP_AGENT_ERROR';

// UI Action Types
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

// WebSocket Action Types
export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT';
export const AGENT_CREATED = 'AGENT_CREATED';
export const AGENT_STARTED = 'AGENT_STARTED';
export const AGENT_STOPPED = 'AGENT_STOPPED';
